from django.urls import path
from .views import (
    base_view,
    country_details,
    city_details,
    search_tickets,
    pricing_view,
    buy_ticket,
    write_comments,
    delete_comment,
    twitter,
    facebook,
    linkedin,
    dribbble,
    dubai_hotel,
    italy_hotel,
    velikobritania_hotel,
    turkey_hotel,
    seoul_hotel,
    velikobritania_country,
    dubai_city,
    italy_country,
    seoul_city,
    turkey_country,
)



urlpatterns = [
    path("", base_view, name="base_view"),
    path("country/details/<int:pk>", country_details, name="country_details"),
    path("city/details/<int:pk>", city_details, name="city_details"),
    path("price/", pricing_view, name="pricing_view"),
    path("tickets/", search_tickets, name="tickets_list"),
    path("buy_tickets/<int:pk>", buy_ticket, name="buy_ticket"),
    path("write_comments/<int:pk>", write_comments, name="write_comments"),
    path("delete_comment/<int:pk>", delete_comment, name="delete_comment"),
    path("twitter/", twitter, name="twitter"),
    path("facebook/", facebook, name="facebook"),
    path("linkedin/", linkedin, name="linkedin"),
    path("dribble/", dribbble, name="dribbble"),
    path("dubai_hotel/", dubai_hotel, name="dubai_hotel"),
    path("italy_hotel/", italy_hotel, name="italy_hotel"),
    path("velikobritania_hotel/", velikobritania_hotel, name="velikobritania_hotel"),
    path("turkey_hotel/", turkey_hotel, name="turkey_hotel"),
    path("seoul_hotel/", seoul_hotel, name="seoul_hotel"),
    path("velikobritania_country/", velikobritania_country, name="velikobritania_country"),
    path("dubai_city/", dubai_city, name="dubai_city"),
    path("italy_country/", italy_country, name="italy_country"),
    path("seoul_city/", seoul_city, name="seoul_city"),
    path("turkey_country/", turkey_country, name="turkey_country"),
]