# Generated by Django 4.2.5 on 2023-10-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_county_city_country_popularplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularplaces',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='blog.city', verbose_name='Город'),
        ),
    ]
