# Generated by Django 4.2.5 on 2023-10-16 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_localplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('standart', 'Standart'), ('buisnes', 'Buisnes')], default='standart', max_length=15)),
                ('budget_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startdart_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buisnes_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='price',
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='image',
            field=models.ImageField(upload_to='populars/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of buing')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='blog.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to='blog.city'),
        ),
    ]
